# Generated by Django 4.2.3 on 2023-08-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_customgroup_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
