# Generated by Django 4.2.3 on 2023-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.TextField(max_length=100)),
                ('receipe_description', models.IntegerField()),
                ('receipe_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
