# Generated by Django 4.2.3 on 2023-08-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='price',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
